/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalTenda;
import javax.swing.JOptionPane; // membuat pesan dialog
import java.sql.*; // untuk menampilkan data dara perintah query
import java.util.*;
/**
 *
 * @author asus
 */
public class formPelanggan extends javax.swing.JFrame {
    
    String judulKolom[]={"kode pelanggan","nama","alamat","no.telp"};
    String sqlPelanggan="SELECT*FROM anggota";
    int lebarKolom[]={100,300,150,100,150,200,400,100};

    /**
     * Creates new form formPelanggan
     */
    public formPelanggan() {
        initComponents();
        this.setLocationRelativeTo(null);
new ConfigDB().tampilTabel(judulKolom, sqlPelanggan, TabelPelanggan);
new ConfigDB().aturLebarKolom(TabelPelanggan, lebarKolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kode_pelanggan = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_no_telp = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_simpan1 = new javax.swing.JButton();
        btn_hapus1 = new javax.swing.JButton();
        btn_clear1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPelanggan = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        btn_refrest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Pelanggan ");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("No.Telp");

        txt_kode_pelanggan.setText("jTextField1");
        txt_kode_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kode_pelangganActionPerformed(evt);
            }
        });

        txt_alamat.setText("jTextField1");
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_nama.setText("jTextField1");
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_no_telp.setText("jTextField1");
        txt_no_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_telpActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_simpan1.setText("Simpan");
        btn_simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan1ActionPerformed(evt);
            }
        });

        btn_hapus1.setText("Hapus");
        btn_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus1ActionPerformed(evt);
            }
        });

        btn_clear1.setText("Clear");
        btn_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear1ActionPerformed(evt);
            }
        });

        TabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPelanggan.setName("JTableFilm"); // NOI18N
        TabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPelanggan);

        txt_cari.setText("Pencarian Pesanan");
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });

        btn_refrest.setText("Refresh");
        btn_refrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_refrest)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_simpan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clear1)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_kode_pelanggan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(71, 71, 71)
                                .addComponent(txt_nama)))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_alamat)
                            .addComponent(txt_no_telp))
                        .addGap(79, 79, 79))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_kode_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_hapus1)
                    .addComponent(btn_simpan1)
                    .addComponent(btn_clear1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refrest))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kode_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kode_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kode_pelangganActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_no_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_telpActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try {
if (
(txt_kode_pelanggan.getText().isEmpty()) &&(txt_nama.getText().isEmpty()) && (txt_alamat.getText().isEmpty())
&&(txt_no_telp.getText().isEmpty())
) {
JOptionPane.showMessageDialog(null,"Silahkan pilih data sebelum proses ubah ");
TabelPelanggan.requestFocus();
} else{
String SQL="UPDATE anggota SET nama='"+txt_nama.getText()+"',alamat='"+txt_alamat.getText()+"', telp='"+txt_no_telp.getText()+"' WHERE kode_pelanggan='"+txt_kode_pelanggan.getText()+"'";
new ConfigDB().ubahData(SQL);
new ConfigDB().tampilTabel(judulKolom, sqlPelanggan, TabelPelanggan);
new ConfigDB().aturLebarKolom(TabelPelanggan, lebarKolom);
}
} catch (Exception e) {
System.out.print(e.toString());
}
        try {
            if (txt_kode_pelanggan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Kode film belum diisi");
                txt_no_telp.requestFocus();
            } else
            if (txt_nama.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Judul film belum diisi");
                txt_alamat.requestFocus();
            } else
            if (txt_kode_pelanggan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Genre film belum diisi");
                txt_no_telp.requestFocus();
            } else
            if (txt_alamat.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Asal negara film belum diisi");
                txt_nama.requestFocus();
            }else
            if (txt_cari.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Stok film belum diisi");
                txt_cari.requestFocus();
            }else
            if (new ConfigDB().duplikasiData("film","KodeFilm",txt_kode_pelanggan.getText())==true){
                JOptionPane.showMessageDialog(null,"Kode Film sudah terdaftar");
                Statement st = new ConfigDB().koneksi.createStatement();
                ResultSet rs = st.executeQuery("SELECT*FROM film WHERE KodeFilm='"+txt_kode_pelanggan.getText()+"'");
                if (rs.next()){
                    txt_kode_pelanggan.setText(rs.getString("kode pelanggan"));
                    txt_no_telp.setText(rs.getString("Nama"));
                    txt_alamat.setText(rs.getString("Alamat"));
                    txt_nama.setText(rs.getString("No.Telp"));
                }
            }else{
                String SQL="INSERT INTO film VALUES ('"+txt_kode_pelanggan.getText()+"','"+txt_nama.getText()+
                        "','"+txt_alamat.getText()+"','"+txt_no_telp.getText()+"')";
                new ConfigDB().simpanData(SQL);
                new ConfigDB().tampilTabel(judulKolom, sqlPelanggan, TabelPelanggan);
                new ConfigDB().aturLebarKolom(TabelPelanggan, lebarKolom);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpan1ActionPerformed

    private void btn_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapus1ActionPerformed

    private void btn_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear1ActionPerformed
        // TODO add your handling code here:
        txt_kode_pelanggan.setText(null);
        txt_nama.setText(null);
        txt_alamat.setText(null);
        txt_no_telp.setText(null);
        
    }//GEN-LAST:event_btn_clear1ActionPerformed

    private void TabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPelangganMouseClicked
        // TODO add your handling code here:
        try {
            int baris = TabelPelanggan.getSelectedRow();
            txt_kode_pelanggan.setText(String.valueOf(TabelPelanggan.getValueAt(baris,0)));
            txt_nama.setText(String.valueOf(TabelPelanggan.getValueAt(baris,1)));
            txt_alamat.setText(String.valueOf(TabelPelanggan.getValueAt(baris,3)));
            txt_no_telp.setText(String.valueOf(TabelPelanggan.getValueAt(baris,4)));
        } catch (Exception e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_TabelPelangganMouseClicked

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
        try {
            String SQL="SELECT*FROM film WHERE judul like '%"+txt_cari.getText()+"%'";
            new ConfigDB().cariData(judulKolom, SQL, TabelPelanggan);
        } catch (Exception e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        try {
String SQL="SELECT*FROM anggota WHERE nama like '%"+txt_cari.getText()+"%'";
new ConfigDB().cariData(judulKolom, SQL, TabelPelanggan);
new ConfigDB().aturLebarKolom(TabelPelanggan, lebarKolom);
} catch (Exception e) {
System.out.print(e.toString());
}
    }//GEN-LAST:event_txt_cariKeyPressed

    private void btn_refrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrestActionPerformed
        // TODO add your handling code here:
        new ConfigDB().tampilTabel(judulKolom, sqlPelanggan, TabelPelanggan);
        new ConfigDB().aturLebarKolom(TabelPelanggan, lebarKolom);
        new ConfigDB().tampilTabel(judulKolom, sqlPelanggan, TabelPelanggan);
        new ConfigDB().aturLebarKolom(TabelPelanggan, lebarKolom);
    }//GEN-LAST:event_btn_refrestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPelanggan;
    private javax.swing.JButton btn_clear1;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus1;
    private javax.swing.JButton btn_refrest;
    private javax.swing.JButton btn_simpan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_kode_pelanggan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no_telp;
    // End of variables declaration//GEN-END:variables
}
