/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalTenda;
    import javax.swing.JOptionPane; // membuat pesan dialog
import java.sql.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author asus
 */
public class RentalTenda extends javax.swing.JFrame {
    
    String judulKolom[]={"Kode Tenda","Ukuran","Jenis","Harga Sewa","Stok Tenda"};
    String sqlFilm="SELECT*FROM film";
    int lebarKolom[]={100,300,100,60,200,60};
     
    public RentalTenda() {
        initComponents();
        this.setLocationRelativeTo(null); // untuk memposisikan form ditengah layar
        new ConfigDB().tampilTabel(judulKolom, sqlFilm, TabelTenda);
        new ConfigDB().aturLebarKolom(TabelTenda, lebarKolom);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kode_tenda = new javax.swing.JTextField();
        cmb_jenis = new javax.swing.JComboBox<>();
        txt_Ukuran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_harga_sewa = new javax.swing.JTextField();
        txt_stok_tenda = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_Ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelTenda = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn_refrest = new javax.swing.JButton();
        txt_pencarian_pesanan = new javax.swing.JTextField();
        btn_hapus1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Tenda");

        jLabel2.setText("Ukuran");

        txt_kode_tenda.setText("jTextField1");
        txt_kode_tenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kode_tendaActionPerformed(evt);
            }
        });

        cmb_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_Ukuran.setText("jTextField1");

        jLabel3.setText("Jenis");

        jLabel4.setText("Harga Sewa");

        jLabel5.setText("Stok Tenda");

        txt_harga_sewa.setText("jTextField1");

        txt_stok_tenda.setText("jTextField1");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_Ubah.setText("Ubah");
        btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        TabelTenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelTenda.setName("JTableFilm"); // NOI18N
        TabelTenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelTendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelTenda);

        btn_refrest.setText("Refresh");
        btn_refrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrestActionPerformed(evt);
            }
        });

        txt_pencarian_pesanan.setText("Pencarian Pesanan");
        txt_pencarian_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pencarian_pesananActionPerformed(evt);
            }
        });
        txt_pencarian_pesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pencarian_pesananKeyPressed(evt);
            }
        });

        btn_hapus1.setText("Clear");
        btn_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_pencarian_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_Ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmb_jenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_kode_tenda)
                                        .addComponent(txt_harga_sewa, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(txt_stok_tenda, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_simpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Ubah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_hapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_hapus1))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btn_refrest)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_kode_tenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_harga_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_stok_tenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_Ubah)
                    .addComponent(btn_hapus)
                    .addComponent(btn_hapus1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_pencarian_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_refrest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahActionPerformed
        // TODO add your handling code here:
        try {
if (
(txt_kode_tenda.getText().isEmpty()) && (txt_Ukuran.getText().isEmpty()) &&
(txt_harga_sewa.getText().isEmpty()) && (txt_stok_tenda.getText().isEmpty()) &&
(String.valueOf(cmb_jenis.getSelectedItem())==".: Pilih Judul :.")
)
{
JOptionPane.showMessageDialog(null,"Silahkan Pilih Data dulu untuk proses Ubah");
TabelTenda.requestFocus();
} else
{
String SQL="UPDATE film SET judul='"+txt_Ukuran.getText()+"', genre='"+String.valueOf(cmb_jenis.getSelectedItem())
+"', tahun='"+txt_harga_sewa.getText()+"', asal='"+txt_stok_tenda.getText()+"', stok='"+"' WHERE KodeTenda='"+txt_kode_tenda.getText()+"'";
new ConfigDB().ubahData(SQL);
new ConfigDB().tampilTabel(judulKolom, sqlFilm, TabelTenda);
new ConfigDB().aturLebarKolom(TabelTenda, lebarKolom);
}
} catch (Exception e)
{
System.out.print(e.toString());
}

    
    
    
    }//GEN-LAST:event_btn_UbahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
if (
(txt_kode_tenda.getText().isEmpty()) && (txt_Ukuran.getText().isEmpty()) &&
(txt_harga_sewa.getText().isEmpty()) && (txt_stok_tenda.getText().isEmpty()) &&
(String.valueOf(cmb_jenis.getSelectedItem())==".: Pilih Judul :.")
)
{
JOptionPane.showMessageDialog(null,"Silahkan Pilih Data dulu untuk proses Hapus");
TabelTenda.requestFocus();
} else
{
String SQL="DELETE FROM film WHERE KodeFilm='"+txt_Ukuran.getText()+"'";
new ConfigDB().hapusData(SQL);
new ConfigDB().tampilTabel(judulKolom, sqlFilm, TabelTenda);
new ConfigDB().aturLebarKolom(TabelTenda, lebarKolom);
}
} catch (Exception e)
{
System.out.print(e.toString());
}
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_refrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrestActionPerformed
        // TODO add your handling code here:
        new ConfigDB().tampilTabel(judulKolom, sqlFilm, TabelTenda);
        new ConfigDB().aturLebarKolom(TabelTenda, lebarKolom);
    }//GEN-LAST:event_btn_refrestActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
       try {
if (txt_kode_tenda.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Kode film belum diisi");
txt_kode_tenda.requestFocus();
} else
if (txt_Ukuran.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Judul film belum diisi");
txt_Ukuran.requestFocus();
} else
if (String.valueOf(cmb_jenis.getSelectedItem())==".: Pilih Judul :."){
JOptionPane.showMessageDialog(null,"Genre film belum diisi");
cmb_jenis.requestFocus();
} else
if (txt_harga_sewa.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Genre film belum diisi");
txt_harga_sewa.requestFocus();
} else
if (txt_stok_tenda.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Asal negara film belum diisi");
txt_stok_tenda.requestFocus();
}else
if (txt_pencarian_pesanan.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Stok film belum diisi");
txt_pencarian_pesanan.requestFocus();
}else
if (new ConfigDB().duplikasiData("film","KodeFilm",txt_kode_tenda.getText())==true){
JOptionPane.showMessageDialog(null,"Kode Film sudah terdaftar");
Statement st = new ConfigDB().koneksi.createStatement();
ResultSet rs = st.executeQuery("SELECT*FROM film WHERE KodeFilm='"+txt_kode_tenda.getText()+"'");
if (rs.next()){
txt_Ukuran.setText(rs.getString("judul"));
cmb_jenis.setSelectedItem(String.valueOf(rs.getString("genre")));
txt_harga_sewa.setText(rs.getString("tahun"));
txt_stok_tenda.setText(rs.getString("asal"));
}
}else{
String SQL="INSERT INTO film VALUES ('"+txt_kode_tenda.getText()+"','"+txt_Ukuran.getText()+"','"+
String.valueOf(cmb_jenis.getSelectedItem()) +"','"+txt_harga_sewa.getText()+"','"+txt_stok_tenda.getText()+"')"; 
new ConfigDB().simpanData(SQL);
new ConfigDB().tampilTabel(judulKolom, sqlFilm, TabelTenda);
new ConfigDB().aturLebarKolom(TabelTenda, lebarKolom);
}
} catch (Exception e) {
}
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_kode_tendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kode_tendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kode_tendaActionPerformed

    private void btn_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus1ActionPerformed
        // TODO add your handling code here:
        txt_kode_tenda.setText(null);
txt_Ukuran.setText(null);
txt_harga_sewa.setText(null);
txt_stok_tenda.setText(null);
cmb_jenis.setSelectedItem(String.valueOf(".: Pilih Judul :."));
    }//GEN-LAST:event_btn_hapus1ActionPerformed

    private void TabelTendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelTendaMouseClicked
        // TODO add your handling code here:
        try {
int baris = TabelTenda.getSelectedRow();
txt_kode_tenda.setText(String.valueOf(TabelTenda.getValueAt(baris,0)));
txt_Ukuran.setText(String.valueOf(TabelTenda.getValueAt(baris,1)));
cmb_jenis.setSelectedItem(String.valueOf(TabelTenda.getValueAt(baris,2)));
txt_harga_sewa.setText(String.valueOf(TabelTenda.getValueAt(baris,3)));
txt_stok_tenda.setText(String.valueOf(TabelTenda.getValueAt(baris,4)));
} catch (Exception e) {
System.out.print(e.toString());
}
    }//GEN-LAST:event_TabelTendaMouseClicked

    private void txt_pencarian_pesananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pencarian_pesananKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pencarian_pesananKeyPressed

    private void txt_pencarian_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pencarian_pesananActionPerformed
        // TODO add your handling code here:
        try {
String SQL="SELECT*FROM film WHERE judul like '%"+txt_pencarian_pesanan.getText()+"%'";
new ConfigDB().cariData(judulKolom, SQL, TabelTenda);
} catch (Exception e) {
System.out.print(e.toString());
}
    }//GEN-LAST:event_txt_pencarian_pesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalTenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalTenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalTenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalTenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalTenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelTenda;
    private javax.swing.JButton btn_Ubah;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hapus1;
    private javax.swing.JButton btn_refrest;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cmb_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Ukuran;
    private javax.swing.JTextField txt_harga_sewa;
    private javax.swing.JTextField txt_kode_tenda;
    private javax.swing.JTextField txt_pencarian_pesanan;
    private javax.swing.JTextField txt_stok_tenda;
    // End of variables declaration//GEN-END:variables
}






//try {
//            if (txt_kode_tenda.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"ID Anggota belum diisi");
//            txt_kode_tenda.requestFocus();
//            }else
//            if(txt_Ukuran.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"Nama Anggota belum diisi");
//            txt_Ukuran.requestFocus();
//            }else
//            if(txt_harga_sewa.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"Tempat Lahir Anggota belum diisi");
//            txt_harga_sewa.requestFocus();
//            }else
//            if(cmb_jenis.getSelectedItem()==".: Pilih Data :."){
//            JOptionPane.showMessageDialog(null,"Jenis Kelamin Anggota belum diisi");
//            cmb_jenis.requestFocus();
//            } else
//            if(txt_stok_tenda.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"ALamat Anggota belum diisi");
//            txt_stok_tenda.requestFocus();
//            }else
//            if(txt_pencarian_pesanan.getText().isEmpty()){
//                
//            JOptionPane.showMessageDialog(null,"Nomor Telp Anggota belum diisi");
//            txt_pencarian_pesanan.requestFocus();
//            } else
//            if (new ConfigDB().duplikasiData("anggota","IDAnggota",txt_kode_tenda.getText())==true){
//            JOptionPane.showMessageDialog(null,"ID Anggota sudah terdaftar");
//            Statement st = new ConfigDB().koneksi.createStatement();
//            ResultSet rs = st.executeQuery("SELECT*FROM anggota WHERE IDAnggota='"+txt_Ukuran.getText()+"'");
//            if(rs.next()){
//            txt_harga_sewa.setText(rs.getString("nama"));
//            txt_stok_tenda.setText(rs.getString("tempat_lahir"));
//            SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
//            txtTGL.setDate(dt.parse(rs.getString("tgl_lahir")));
//            cmbJKL.setSelectedItem(String.valueOf(rs.getString("jkl")));
//            cmbStatus.setSelectedItem(String.valueOf(rs.getString("status")));
//            txtAlamat.setText(rs.getString("alamat"));
//            txtTelp.setText(rs.getString("telp"));
//            }
//            }
//            else{
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
//            String TGL =sdf.format(txtTGL.getDate());
//            String SQL ="INSERT INTO anggota VALUES ('"+txtID.getText()+"','"+txtNama.getText()+"','"+txtTempat.getText()
//            +"','"+TGL+"','"+String.valueOf(cmbJKL.getSelectedItem()) +"','"+String.valueOf(cmbStatus.getSelectedItem())
//            +"','"+txtAlamat.getText()+"','"+txtTelp.getText()+"')";
//            new ConfigDB().simpanData(SQL);
//            new ConfigDB().tampilTabel(judulKolom, sqlAnggota, JTableAnggota);
//            new ConfigDB().aturLebarKolom(JTableAnggota, lebarKolom);
//            }
//            } catch (Exception e) {
//            System.out.print(e.toString());
//            }